#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

polybar --config=~/.config/polybar/themes/classic/config &
xset led 3 &
picom --experimental-backends -b &
discord &


bspc monitor -d I II III IV V VI VII VIII 

bspc config border_width         1
bspc config window_gap           9
bspc config border_radius        15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#Make bf4 playable in bspwm
bspc rule -a steam_app_1182480 state=floating
bspc rule -a steam_app_1238860 state=floating
#Make gta5 playable in bspwm
bspc rule -a steam_app_271590 state=floating

#Make SHOC playable
bspc rule -a steam_app_4500 state=floating

bspc config normal_border_color "#FFFFFF"
bspc config focused_border_color "#FF0B5C"
